In [17]:
# pip install python-doctr[torch] surya-ocr keras-ocr transformers sentencepiece

Collecting surya-ocr
  Using cached surya_ocr-0.22.1-py3-none-any.whl.metadata (27 kB)
Collecting keras-ocr
  Using cached keras_ocr-0.9.3-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: transformers in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (5.14.1)
Collecting sentencepiece
  Downloading sentencepiece-0.2.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (33 kB)
Collecting python-doctr[torch]
  Downloading python_doctr-1.1.0-py3-none-any.whl.metadata (34 kB)
WARNING: python-doctr 1.1.0 does not provide the extra 'torch'
Requirement already satisfied: torch<3.0.0,>=2.0.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (2.13.0)
Requirement already satisfied: torchvision>=0.15.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (0.28.0)
Collecting onnx<3.0.0,>=1.12.0 (from python-doctr[torch])
  Downloading onnx-1.22.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.16.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (2.3.5)
Requirement already satisfied: scipy<2.0.0,>=1.4.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.18.0)
Collecting h5py<4.0.0,>=3.1.0 (from python-doctr[torch])
  Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: opencv-python<6.0.0,>=4.5.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (5.0.0.93)
Requirement already satisfied: pypdfium2<6.0.0,>=4.11.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (5.13.0)
Requirement already satisfied: pyclipper<2.0.0,>=1.2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.4.0)
Requirement already satisfied: shapely<3.0.0,>=1.6.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (2.1.2)
Requirement already satisfied: langdetect<2.0.0,>=1.0.9 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.0.9)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from python-doctr[torch])
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: huggingface-hub<2.0.0,>=0.20.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.27.0)
Requirement already satisfied: Pillow>=10.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (12.3.0)
Collecting anyascii>=0.3.2 (from python-doctr[torch])
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting validators>=0.18.0 (from python-doctr[torch])
  Downloading validators-0.35.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>=4.30.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (4.70.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (3.32.2)
Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (6.0.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (4.16.0)
Requirement already satisfied: anyio in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (4.14.2)
Requirement already satisfied: certifi in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (1.0.9)
Requirement already satisfied: idna in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (3.18)
Requirement already satisfied: h11>=0.16 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0.0,>=0.20.0->python-doctr[torch]) (0.16.0)
Requirement already satisfied: six in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from langdetect<2.0.0,>=1.0.9->python-doctr[torch]) (1.17.0)
Requirement already satisfied: protobuf>=4.25.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from onnx<3.0.0,>=1.12.0->python-doctr[torch]) (7.36.0)
Collecting ml_dtypes>=0.5.4 (from onnx<3.0.0,>=1.12.0->python-doctr[torch])
  Downloading ml_dtypes-0.6.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.8 kB)
Requirement already satisfied: setuptools>=77.0.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (3.6.1)
Requirement already satisfied: jinja2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch<3.0.0,>=2.0.0->python-doctr[torch]) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch<3.0.0,>=2.0.0->python-doctr[torch]) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch<3.0.0,>=2.0.0->python-doctr[torch]) (1.6.0)
Requirement already satisfied: beautifulsoup4<5,>=4.12.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (4.15.0)
Collecting filetype<2,>=1.2.0 (from surya-ocr)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting openai<3,>=1.55.0 (from surya-ocr)
  Downloading openai-2.54.0-py3-none-any.whl.metadata (40 kB)
Collecting opencv-python-headless==4.11.0.86 (from surya-ocr)
  Downloading opencv_python_headless-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting Pillow>=10.1.0 (from python-doctr[torch])
  Downloading pillow-10.4.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (9.2 kB)
Requirement already satisfied: platformdirs<5,>=4.3.6 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (4.11.1)
Requirement already satisfied: pydantic-settings<3,>=2.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (2.15.0)
Requirement already satisfied: pydantic<3,>=2.5.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=1.0.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (1.2.3)
Requirement already satisfied: requests<3,>=2.28.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (2.34.2)
Requirement already satisfied: soupsieve>=1.6.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from beautifulsoup4<5,>=4.12.0->surya-ocr) (2.9.2)
Collecting distro<2,>=1.7.0 (from openai<3,>=1.55.0->surya-ocr)
  Downloading distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting jiter<1,>=0.10.0 (from openai<3,>=1.55.0->surya-ocr)
  Using cached jiter-0.16.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.2 kB)
Collecting sniffio (from openai<3,>=1.55.0->surya-ocr)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic<3,>=2.5.3->surya-ocr) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic<3,>=2.5.3->surya-ocr) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic<3,>=2.5.3->surya-ocr) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.28.0->surya-ocr) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.28.0->surya-ocr) (2.7.0)
Collecting editdistance (from keras-ocr)
  Downloading editdistance-0.8.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting efficientnet==1.0.0 (from keras-ocr)
  Downloading efficientnet-1.0.0-py3-none-any.whl.metadata (6.1 kB)
Collecting essential_generators (from keras-ocr)
  Downloading essential_generators-1.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: fonttools in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from keras-ocr) (4.63.0)
Collecting imgaug (from keras-ocr)
  Downloading imgaug-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting keras-applications<=1.0.8,>=1.0.7 (from efficientnet==1.0.0->keras-ocr)
  Downloading Keras_Applications-1.0.8-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: scikit-image in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from efficientnet==1.0.0->keras-ocr) (0.26.0)
Requirement already satisfied: regex>=2025.10.22 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from transformers) (0.27.1)
Requirement already satisfied: safetensors>=0.8.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from transformers) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from sympy>=1.13.3->torch<3.0.0,>=2.0.0->python-doctr[torch]) (1.3.0)
Requirement already satisfied: matplotlib in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from imgaug->keras-ocr) (3.11.1)
Requirement already satisfied: imageio in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from imgaug->keras-ocr) (2.37.4)
Requirement already satisfied: tifffile>=2022.8.12 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from scikit-image->efficientnet==1.0.0->keras-ocr) (2026.8.16)
Requirement already satisfied: lazy-loader>=0.4 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from scikit-image->efficientnet==1.0.0->keras-ocr) (0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from jinja2->torch<3.0.0,>=2.0.0->python-doctr[torch]) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from matplotlib->imgaug->keras-ocr) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from matplotlib->imgaug->keras-ocr) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from matplotlib->imgaug->keras-ocr) (1.5.0)
Requirement already satisfied: pyparsing>=3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from matplotlib->imgaug->keras-ocr) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from matplotlib->imgaug->keras-ocr) (2.9.0.post0)
Requirement already satisfied: shellingham>=1.3.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading python_doctr-1.1.0-py3-none-any.whl (402 kB)
Downloading h5py-3.16.0-cp312-cp312-manylinux_2_28_x86_64.whl (5.4 MB)

In [12]:
# pip install tensorflow tiktoken sentencepiece

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl.metadata (4.4 kB)
Collecting tiktoken
  Downloading tiktoken-0.14.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: sentencepiece in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (0.2.2)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: flatbuffers>=25.9.23 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (25.12.19)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
Requirement already satisfied: opt_einsum>=2.3.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (7.36.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (1.83.0)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.26.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (2.3.5)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.7 kB)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: regex in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from tiktoken) (2026.7.19)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: rich in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.20.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp312-cp312-manylinux_2_27_x86_64.whl (572.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.6/572.6 MB 77.0 MB/s  0:00:04m0:00:0100:01
Downloading h5py-3.14.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 26.0 MB/s  0:00:00
Downloading tiktoken-0.14.0-cp312-cp312-manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 23.3 MB/s  0:00:00
Downloading absl_py-2.5.0-py3-none-any.whl (137 kB)
Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading wheel-0.48.0-py3-none-any.whl (33 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.15.1-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 30.7 MB/s  0:00:00
Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 80.0 MB/s  0:00:006m0:00:01
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.20.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (488 kB)
Installing collected packages: namex, libclang, wheel, termcolor, optree, h5py, google_pasta, gast, absl-py, tiktoken, astunparse, keras, tensorflow
  Attempting uninstall: h5pym╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [optree]g]
    Found existing installation: h5py 3.16.0━━━━━━━━━━━━━━━━━━  4/13 [optree]
    Uninstalling h5py-3.16.0:m━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/13 [optree]
      Successfully uninstalled h5py-3.16.0━━━━━━━━━━━━━━━━━━━━  4/13 [optree]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [tensorflow]3 [tensorflow]a]
Successfully installed absl-py-2.5.0 astunparse-1.6.3 gast-0.7.0 google_pasta-0.2.0 h5py-3.14.0 keras-3.15.1 libclang-18.1.1 namex-0.1.0 optree-0.20.0 tensorflow-2.21.0 termcolor-3.3.0 tiktoken-0.14.0 wheel-0.48.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
# import os
# import time
# import pandas as pd
# import numpy as np
# import gc
# from PIL import Image
# import pymupdf

In [8]:
# # --- Setup Directories & Target Files ---
# test_dir = "benchmark_test_files"
# output_text_dir = "output_ocr_comparison"
# os.makedirs(output_text_dir, exist_ok=True)

# # Generate the exact list of 10 target files
# target_files = [f"image_based_{i}.pdf" for i in range(1, 11)]

# # Helper function to save text
# def save_text_to_file(original_file, library_name, extracted_text):
#     if extracted_text:
#         safe_name = f"{original_file}_{library_name}.txt"
#         out_path = os.path.join(output_text_dir, safe_name)
#         with open(out_path, "w", encoding="utf-8") as f:
#             f.write(extracted_text)

# print("Initializing OCR Engines...")
# models_ready = {}

Initializing OCR Engines...

In [ ]:
# # 1. EasyOCR
# try:
#     import easyocr
#     easy_reader = easyocr.Reader(['en'], gpu=False, verbose=False)
#     models_ready['EasyOCR'] = True
# except Exception as e:
#     print(f"EasyOCR Init Warning: {e}")
#     models_ready['EasyOCR'] = False

In [4]:
# # 2. PaddleOCR 
# try:
#     from paddleocr import PaddleOCR
#     paddle_reader = PaddleOCR(use_textline_orientation=False, lang='en', enable_mkldnn=False)
#     models_ready['PaddleOCR'] = True
# except Exception as e:
#     print(f"PaddleOCR Init Warning: {e}")
#     models_ready['PaddleOCR'] = False

Creating model: ('PP-LCNet_x1_0_doc_ori', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-LCNet_x1_0_doc_ori`.
Creating model: ('UVDoc', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/UVDoc`.
Creating model: ('PP-OCRv6_medium_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-OCRv6_medium_det`.
Creating model: ('PP-OCRv6_medium_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-OCRv6_medium_rec`.

In [9]:
# # 3. RapidOCR
# try:
#     from rapidocr_onnxruntime import RapidOCR
#     rapid_reader = RapidOCR()
#     models_ready['RapidOCR'] = True
# except Exception as e:
#     print(f"RapidOCR Init Warning: {e}")
#     models_ready['RapidOCR'] = False

In [5]:
# # 4. DocTR
# try:
#     from doctr.models import ocr_predictor
#     doctr_model = ocr_predictor(pretrained=True)
#     models_ready['DocTR'] = True
# except Exception as e:
#     print(f"DocTR Init Warning: {e}")
#     models_ready['DocTR'] = False

Downloading https://doctr-static.mindee.com/models?id=v0.8.1/fast_base-688a8b34.pt&src=0 to /home/jupyter-user/.cache/doctr/models/fast_base-688a8b34.pt

65815552it [00:00, 126962410.36it/s]

Downloading https://doctr-static.mindee.com/models?id=v0.12.0/crnn_vgg16_bn-0417f351.pt&src=0 to /home/jupyter-user/.cache/doctr/models/crnn_vgg16_bn-0417f351.pt

63303680it [00:00, 161961434.13it/s]

In [6]:
# # 5. Keras-OCR
# try:
#     import keras_ocr
#     keras_pipeline = keras_ocr.pipeline.Pipeline()
#     models_ready['Keras-OCR'] = True
# except Exception as e:
#     print(f"Keras-OCR Init Warning: {e}")
#     models_ready['Keras-OCR'] = False

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787889687.257261  333889 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1787889687.351327  333889 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1787889689.213843  333889 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Keras-OCR Init Warning: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.

NameError: name 'models_ready' is not defined

In [7]:
# # 6. Surya OCR
# try:
#     from surya.ocr import run_ocr
#     from surya.model.detection.segformer import load_model as load_det_model, load_processor as load_det_processor
#     from surya.model.recognition.model import load_model as load_rec_model
#     from surya.model.recognition.processor import load_processor as load_rec_processor
#     surya_det_model, surya_det_processor = load_det_model(), load_det_processor()
#     surya_rec_model, surya_rec_processor = load_rec_model(), load_rec_processor()
#     models_ready['Surya'] = True
# except Exception as e:
#     print(f"Surya OCR Init Warning: {e}")
#     models_ready['Surya'] = False

Surya OCR Init Warning: No module named 'surya.ocr'

In [8]:
# # 7. TrOCR (HuggingFace)
# try:
#     from transformers import TrOCRProcessor, VisionEncoderDecoderModel
#     trocr_processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-printed")
#     trocr_model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-printed")
#     models_ready['TrOCR'] = True
# except Exception as e:
#     print(f"TrOCR Init Warning: {e}")
#     models_ready['TrOCR'] = False

TrOCR Init Warning: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece or tiktoken installed to convert a slow tokenizer to a fast one.

In [9]:
# results = []
# print(f"\n Starting Extended Benchmark on {len(target_files)} target files...\n")

# for file_name in target_files:
#     file_path = os.path.join(test_dir, file_name)
    
#     if not os.path.exists(file_path):
#         print(f" Skipping {file_name}: File not found in directory.")
#         continue
        
#     print(f"Analyzing: {file_name}...")
    
#     # Render PDF pages to images
#     doc = pymupdf.open(file_path)
#     img_arrays = []
#     pil_images = []
#     for page in doc:
#         pix = page.get_pixmap(dpi=150)
#         img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
#         pil_images.append(img)
#         img_arrays.append(np.array(img))
        
#     # --- 1. EasyOCR ---
#     # if models_ready.get('EasyOCR'):
#     #     t0 = time.time()
#     #     try:
#     #         text = "\n".join([" ".join(easy_reader.readtext(arr, detail=0)) for arr in img_arrays])
#     #         save_text_to_file(file_name, "EasyOCR", text)
#     #     except Exception: text = ""
#     #     results.append({"File": file_name, "Tool": "EasyOCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 2. PaddleOCR ---
#     if models_ready.get('PaddleOCR'):
#         t0 = time.time()
#         try:
#             text = ""
#             for arr in img_arrays:
#                 res = paddle_reader.predict(arr)
#                 if res and res[0]:
#                     text += "\n".join([line[1][0] for line in res[0]]) + "\n"
#             save_text_to_file(file_name, "PaddleOCR", text)
#         except Exception: text = ""
#         results.append({"File": file_name, "Tool": "PaddleOCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 3. RapidOCR ---
#     # if models_ready.get('RapidOCR'):
#     #     t0 = time.time()
#     #     try:
#     #         text = ""
#     #         for arr in img_arrays:
#     #             res, _ = rapid_reader(arr)
#     #             if res:
#     #                 text += "\n".join([line[1] for line in res]) + "\n"
#     #         save_text_to_file(file_name, "RapidOCR", text)
#     #     except Exception: text = ""
#     #     results.append({"File": file_name, "Tool": "RapidOCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 4. DocTR ---
#     if models_ready.get('DocTR'):
#         t0 = time.time()
#         try:
#             text = ""
#             doc_res = doctr_model(img_arrays)
#             for page in doc_res.pages:
#                 for block in page.blocks:
#                     for line in block.lines:
#                         text += " ".join([word.value for word in line.words]) + "\n"
#             save_text_to_file(file_name, "DocTR", text)
#         except Exception: text = ""
#         results.append({"File": file_name, "Tool": "DocTR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 5. Keras-OCR ---
#     if models_ready.get('Keras-OCR'):
#         t0 = time.time()
#         try:
#             text = ""
#             prediction_groups = keras_pipeline.recognize(img_arrays)
#             for group in prediction_groups:
#                 text += " ".join([word_info[0] for word_info in group]) + "\n"
#             save_text_to_file(file_name, "Keras-OCR", text)
#         except Exception: text = ""
#         results.append({"File": file_name, "Tool": "Keras-OCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 6. Surya OCR ---
#     if models_ready.get('Surya'):
#         t0 = time.time()
#         try:
#             text = ""
#             langs = [["en"] for _ in pil_images]
#             predictions = run_ocr(pil_images, langs, surya_det_model, surya_det_processor, surya_rec_model, surya_rec_processor)
#             for pred in predictions:
#                 text += "\n".join([line.text for line in pred.text_lines]) + "\n"
#             save_text_to_file(file_name, "SuryaOCR", text)
#         except Exception: text = ""
#         results.append({"File": file_name, "Tool": "SuryaOCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

#     # --- 7. TrOCR ---
#     if models_ready.get('TrOCR'):
#         t0 = time.time()
#         try:
#             # TrOCR is designed for single cropped lines, not full pages.
#             # Passing a full page directly will usually yield low chars or a crash.
#             text = ""
#             for img in pil_images:
#                 pixel_values = trocr_processor(images=img, return_tensors="pt").pixel_values
#                 generated_ids = trocr_model.generate(pixel_values)
#                 text += trocr_processor.batch_decode(generated_ids, skip_special_tokens=True)[0] + "\n"
#             save_text_to_file(file_name, "TrOCR", text)
#         except Exception: text = ""
#         results.append({"File": file_name, "Tool": "TrOCR", "Time (s)": round(time.time() - t0, 4), "Chars": len(text.strip())})

        
#     # Free up memory between files
#     gc.collect()

 Starting Extended Benchmark on 10 target files...

Analyzing: image_based_1.pdf...
Analyzing: image_based_2.pdf...
Analyzing: image_based_3.pdf...
Analyzing: image_based_4.pdf...
Analyzing: image_based_5.pdf...
Analyzing: image_based_6.pdf...
Analyzing: image_based_7.pdf...
Analyzing: image_based_8.pdf...
Analyzing: image_based_9.pdf...
Analyzing: image_based_10.pdf...

In [11]:
# # --- Final Output ---
# df_benchmark = pd.DataFrame(results)
# print("\n OCR BENCHMARK COMPLETE!")
# display(df_benchmark)

 OCR BENCHMARK COMPLETE!

                  File       Tool  Time (s)  Chars
0    image_based_1.pdf  PaddleOCR   78.1874     29
1    image_based_1.pdf      DocTR    7.5783   3270
2    image_based_2.pdf  PaddleOCR   65.8863     29
3    image_based_2.pdf      DocTR    4.8673   1829
4    image_based_3.pdf  PaddleOCR  106.3292     29
5    image_based_3.pdf      DocTR    6.3431   2418
6    image_based_4.pdf  PaddleOCR   56.0600     29
7    image_based_4.pdf      DocTR    5.8124   2033
8    image_based_5.pdf  PaddleOCR   53.0973     29
9    image_based_5.pdf      DocTR    5.3784   2077
10   image_based_6.pdf  PaddleOCR   54.0871     29
11   image_based_6.pdf      DocTR    4.6270   2029
12   image_based_7.pdf  PaddleOCR   77.6476     29
13   image_based_7.pdf      DocTR    7.6788   3272
14   image_based_8.pdf  PaddleOCR   59.7084     29
15   image_based_8.pdf      DocTR    4.9316   1763
16   image_based_9.pdf  PaddleOCR   58.9510     29
17   image_based_9.pdf      DocTR    4.9047   1793
18  image_based_10.pdf  PaddleOCR  157.2676     29
19  image_based_10.pdf      DocTR    6.2747   2272

In [2]:
# import tracemalloc
# import time

# # Example for EasyOCR block:
# if models_ready.get('EasyOCR'):
#     t0 = time.time()
#     tracemalloc.start() # Start memory tracker
    
#     try:
#         text = "\n".join([" ".join(easy_reader.readtext(arr, detail=0)) for arr in img_arrays])
#     except Exception: 
#         text = ""
        
#     current, peak = tracemalloc.get_traced_memory() # Get memory usage
#     tracemalloc.stop() # Stop tracker
    
#     peak_mb = peak / (1024 * 1024) # Convert bytes to Megabytes
#     time_taken = time.time() - t0
    
#     results.append({
#         "File": file_name, 
#         "Tool": "EasyOCR", 
#         "Time (s)": round(time_taken, 4), 
#         "Peak Memory (MB)": round(peak_mb, 2),
#         "Chars": len(text.strip())
#     })

NameError: name 'models_ready' is not defined

In [4]:
# pip install jiwer

Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: click>=8.1.8 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from jiwer) (8.4.2)
Requirement already satisfied: rapidfuzz>=3.9.7 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from jiwer) (3.14.5)
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Installing collected packages: jiwer
Successfully installed jiwer-4.0.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
# import os
# from jiwer import cer, wer

# output_dir = "output_ocr_comparison"
# target_file = "image_based_1.pdf" 

# # baseline (the most accurate model you've tested visually)
# baseline_tool = "DocTR"
# comparison_tools = ["EasyOCR", "RapidOCR"]

# def load_text(filename):
#     path = os.path.join(output_dir, filename)
#     if os.path.exists(path):
#         with open(path, "r", encoding="utf-8") as f:
#             return f.read().strip()
#     return ""

# baseline_text = load_text(f"{target_file}_{baseline_tool}.txt")

# if not baseline_text:
#     print(f" Baseline text for {baseline_tool} not found.")
# else:
#     print(f" ACCURACY COMPARISON FOR: {target_file} (Baseline: {baseline_tool})")
#     print("-" * 60)
    
#     for tool in comparison_tools:
#         tool_text = load_text(f"{target_file}_{tool}.txt")
#         if tool_text:
#             # CER: Character Error Rate | WER: Word Error Rate
#             char_error = cer(baseline_text, tool_text)
#             word_error = wer(baseline_text, tool_text)
            
#             # Convert error rate to accuracy percentage
#             char_accuracy = max(0, (1 - char_error) * 100)
#             word_accuracy = max(0, (1 - word_error) * 100)
            
#             print(f" {tool}:")
#             print(f"   - Character Accuracy: {char_accuracy:.1f}%")
#             print(f"   - Word Accuracy:      {word_accuracy:.1f}%\n")

 ACCURACY COMPARISON FOR: image_based_1.pdf (Baseline: DocTR)
------------------------------------------------------------
 EasyOCR:
   - Character Accuracy: 95.3%
   - Word Accuracy:      61.8%

 RapidOCR:
   - Character Accuracy: 87.3%
   - Word Accuracy:      9.4%

In [10]:
pip install easyocr rapidocr-onnxruntime paddleocr paddlepaddle surya-ocr python-doctr[torch] pymupdf pandas numpy pillow jiwer

Requirement already satisfied: easyocr in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (1.7.2)
Requirement already satisfied: rapidocr-onnxruntime in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (1.4.4)
Requirement already satisfied: paddleocr in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (3.7.0)
Requirement already satisfied: paddlepaddle in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (3.3.1)
Requirement already satisfied: surya-ocr in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (0.22.1)
Requirement already satisfied: pymupdf in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (1.28.2)
Requirement already satisfied: pandas in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (2.3.5)
Requirement already satisfied: pillow in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (10.4.0)
Requirement already satisfied: jiwer in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (4.0.0)
Requirement already satisfied: python-doctr[torch] in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (1.1.0)
Requirement already satisfied: torch in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (2.13.0)
Requirement already satisfied: torchvision>=0.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (0.28.0)
Requirement already satisfied: opencv-python-headless in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (4.11.0.86)
Requirement already satisfied: scipy in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (1.18.0)
Requirement already satisfied: scikit-image in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (0.26.0)
Requirement already satisfied: python-bidi in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (0.6.11)
Requirement already satisfied: PyYAML in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (6.0.2)
Requirement already satisfied: Shapely in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (2.1.2)
Requirement already satisfied: pyclipper in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (1.4.0)
Requirement already satisfied: ninja in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from easyocr) (1.13.0)
Requirement already satisfied: opencv-python>=4.5.1.48 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rapidocr-onnxruntime) (5.0.0.93)
Requirement already satisfied: six>=1.15.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rapidocr-onnxruntime) (1.17.0)
Requirement already satisfied: onnxruntime>=1.7.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rapidocr-onnxruntime) (1.29.0)
Requirement already satisfied: tqdm in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from rapidocr-onnxruntime) (4.70.0)
Requirement already satisfied: paddlex<3.8.0,>=3.7.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (3.7.2)
Requirement already satisfied: requests in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddleocr) (2.34.2)
Requirement already satisfied: aiohttp>=3.8.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddleocr) (3.14.3)
Requirement already satisfied: typing-extensions>=4.12 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddleocr) (4.16.0)
Requirement already satisfied: aistudio-sdk>=0.3.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (0.3.9)
Requirement already satisfied: chardet in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (7.6.0)
Requirement already satisfied: colorlog in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (6.12.0)
Requirement already satisfied: filelock in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (3.32.2)
Requirement already satisfied: huggingface-hub in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (1.27.0)
Requirement already satisfied: modelscope>=1.28.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (1.39.1)
Requirement already satisfied: packaging in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (26.3)
Requirement already satisfied: prettytable in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (3.18.0)
Requirement already satisfied: py-cpuinfo in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (9.0.0)
Requirement already satisfied: pydantic>=2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (2.13.4)
Requirement already satisfied: ruamel.yaml in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (0.19.1)
Requirement already satisfied: ujson in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (5.13.0)
Requirement already satisfied: imagesize in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (2.0.1)
Requirement already satisfied: opencv-contrib-python==4.10.0.84 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (4.10.0.84)
Requirement already satisfied: pypdfium2>=4 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (5.13.0)
Requirement already satisfied: httpx in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (0.28.1)
Requirement already satisfied: protobuf>=3.20.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (7.36.0)
Requirement already satisfied: opt_einsum==3.3.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (3.3.0)
Requirement already satisfied: networkx in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (3.6.1)
Requirement already satisfied: safetensors>=0.6.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (0.8.0)
Requirement already satisfied: setuptools in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from paddlepaddle) (84.0.0)
Requirement already satisfied: beautifulsoup4<5,>=4.12.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (4.15.0)
Requirement already satisfied: click<9,>=8.1.8 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (8.4.2)
Requirement already satisfied: filetype<2,>=1.2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (1.2.0)
Requirement already satisfied: openai<3,>=1.55.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (2.54.0)
Requirement already satisfied: platformdirs<5,>=4.3.6 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (4.11.1)
Requirement already satisfied: pydantic-settings<3,>=2.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (2.15.0)
Requirement already satisfied: python-dotenv<2,>=1.0.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (1.2.3)
Requirement already satisfied: transformers>=5.12.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from surya-ocr) (5.14.1)
Requirement already satisfied: soupsieve>=1.6.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from beautifulsoup4<5,>=4.12.0->surya-ocr) (2.9.2)
Requirement already satisfied: anyio in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx->paddlepaddle) (4.14.2)
Requirement already satisfied: certifi in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx->paddlepaddle) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx->paddlepaddle) (1.0.9)
Requirement already satisfied: idna in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpx->paddlepaddle) (3.18)
Requirement already satisfied: h11>=0.16 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from httpcore==1.*->httpx->paddlepaddle) (0.16.0)
Requirement already satisfied: fsspec>=2023.5.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from huggingface-hub->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (1.6.0)
Requirement already satisfied: distro<2,>=1.7.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from openai<3,>=1.55.0->surya-ocr) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from openai<3,>=1.55.0->surya-ocr) (0.16.0)
Requirement already satisfied: sniffio in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from openai<3,>=1.55.0->surya-ocr) (1.3.1)
Requirement already satisfied: annotated-types>=0.6.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic>=2->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic>=2->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pydantic>=2->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests->paddleocr) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from requests->paddleocr) (2.7.0)
Requirement already satisfied: sympy>=1.13.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (1.14.0)
Requirement already satisfied: jinja2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.0.3.0)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from torch->easyocr) (3.7.1)
Requirement already satisfied: nvidia-cublas==13.1.1.3.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.1.1.3)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.0.88)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (12.0.0.61)
Requirement already satisfied: nvidia-nvjitlink<14,>=13.0.88 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.3.33)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (12.6.3.3)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.3; platform_system == "Linux"->torch->easyocr) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from cuda-bindings<14,>=13.0.3->torch->easyocr) (1.6.0)
WARNING: python-doctr 1.1.0 does not provide the extra 'torch'
Requirement already satisfied: onnx<3.0.0,>=1.12.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.22.0)
Requirement already satisfied: h5py<4.0.0,>=3.1.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (3.14.0)
Requirement already satisfied: langdetect<2.0.0,>=1.0.9 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (1.0.9)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (3.14.5)
Requirement already satisfied: anyascii>=0.3.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (0.3.3)
Requirement already satisfied: validators>=0.18.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from python-doctr[torch]) (0.35.0)
Requirement already satisfied: ml_dtypes>=0.5.4 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from onnx<3.0.0,>=1.12.0->python-doctr[torch]) (0.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aiohttp>=3.8.0->paddleocr) (1.24.5)
Requirement already satisfied: psutil in /home/jupyter-user/gender-classification-env/lib/python3.12/site-packages (from aistudio-sdk>=0.3.5->paddlex<3.8.0,>=3.7.0->paddlex[ocr-core]<3.8.0,>=3.7.0->paddleocr) (7.2.2)

In [11]:
import os
import time
import tracemalloc
import pandas as pd
import numpy as np
import gc
from PIL import Image
import pymupdf

In [12]:
# --- 1. Setup Directories & Target Files ---
test_dir = "benchmark_test_files"
output_text_dir = "output_ocr_comparison_new"
os.makedirs(output_text_dir, exist_ok=True)

target_files = [f"image_based_{i}.pdf" for i in range(1, 11)]

def save_text_to_file(original_file, library_name, extracted_text):
    if extracted_text:
        safe_name = f"{original_file}_{library_name}.txt"
        out_path = os.path.join(output_text_dir, safe_name)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(extracted_text)

In [4]:
# --- 2. Initialize Models Safely ---
print("⏳ Initializing OCR Engines...")
models_ready = {}

⏳ Initializing OCR Engines...

In [13]:
# EasyOCR
try:
    import easyocr
    easy_reader = easyocr.Reader(['en'], gpu=False, verbose=False)
    models_ready['EasyOCR'] = True
except Exception as e:
    print(f"EasyOCR Init Warning: {e}")
    models_ready['EasyOCR'] = False

In [14]:
# RapidOCR
try:
    from rapidocr_onnxruntime import RapidOCR
    rapid_reader = RapidOCR()
    models_ready['RapidOCR'] = True
except Exception as e:
    print(f"RapidOCR Init Warning: {e}")
    models_ready['RapidOCR'] = False

In [15]:
# PaddleOCR
try:
    from paddleocr import PaddleOCR
    paddle_reader = PaddleOCR(use_textline_orientation=False, lang='en', enable_mkldnn=False)
    models_ready['PaddleOCR'] = True
except Exception as e:
    print(f"PaddleOCR Init Warning: {e}")
    models_ready['PaddleOCR'] = False

Creating model: ('PP-LCNet_x1_0_doc_ori', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-LCNet_x1_0_doc_ori`.
Creating model: ('UVDoc', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/UVDoc`.
Creating model: ('PP-OCRv6_medium_det', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-OCRv6_medium_det`.
Creating model: ('PP-OCRv6_medium_rec', None, None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `/home/jupyter-user/.paddlex/official_models/PP-OCRv6_medium_rec`.

In [16]:
# DocTR
try:
    from doctr.models import ocr_predictor
    doctr_model = ocr_predictor(pretrained=True)
    models_ready['DocTR'] = True
except Exception as e:
    print(f"DocTR Init Warning: {e}")
    models_ready['DocTR'] = False

In [19]:
# Surya OCR
try:
    from surya.recognition import RecognitionPredictor
    from surya.detection import DetectionPredictor
    
    surya_det_predictor = DetectionPredictor()
    surya_rec_predictor = RecognitionPredictor()
    models_ready['SuryaOCR'] = True
except Exception as e:
    print(f"Surya OCR Init Warning: {e}")
    models_ready['SuryaOCR'] = False

In [20]:
# --- 3. Execution & Measurement Loop ---
results = []
print(f"\n🚀 Starting Benchmark on target files...\n")

for file_name in target_files:
    file_path = os.path.join(test_dir, file_name)
    
    if not os.path.exists(file_path):
        print(f"⚠️ Skipping {file_name}: File not found.")
        continue
        
    print(f"Analyzing: {file_name}...")
    
    doc = pymupdf.open(file_path)
    img_arrays = []
    pil_images = []
    for page in doc:
        pix = page.get_pixmap(dpi=150)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        pil_images.append(img)
        img_arrays.append(np.array(img))
        
    # EasyOCR
    if models_ready.get('EasyOCR'):
        tracemalloc.start()
        t0 = time.time()
        try:
            text = "\n".join([" ".join(easy_reader.readtext(arr, detail=0)) for arr in img_arrays])
            save_text_to_file(file_name, "EasyOCR", text)
        except Exception: text = ""
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        results.append({"File": file_name, "Tool": "EasyOCR", "Time (s)": round(time.time() - t0, 4), "Memory (MB)": round(peak / 10**6, 2), "Chars": len(text.strip())})

    # RapidOCR
    if models_ready.get('RapidOCR'):
        tracemalloc.start()
        t0 = time.time()
        try:
            text = ""
            for arr in img_arrays:
                res, _ = rapid_reader(arr)
                if res: text += "\n".join([line[1] for line in res]) + "\n"
            save_text_to_file(file_name, "RapidOCR", text)
        except Exception: text = ""
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        results.append({"File": file_name, "Tool": "RapidOCR", "Time (s)": round(time.time() - t0, 4), "Memory (MB)": round(peak / 10**6, 2), "Chars": len(text.strip())})

    # PaddleOCR
    if models_ready.get('PaddleOCR'):
        tracemalloc.start()
        t0 = time.time()
        try:
            text = ""
            for arr in img_arrays:
                res = paddle_reader.predict(arr)
                if res and res[0]: text += "\n".join([line[1][0] for line in res[0]]) + "\n"
            save_text_to_file(file_name, "PaddleOCR", text)
        except Exception: text = ""
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        results.append({"File": file_name, "Tool": "PaddleOCR", "Time (s)": round(time.time() - t0, 4), "Memory (MB)": round(peak / 10**6, 2), "Chars": len(text.strip())})

    # DocTR
    if models_ready.get('DocTR'):
        tracemalloc.start()
        t0 = time.time()
        try:
            text = ""
            doc_res = doctr_model(img_arrays)
            for page in doc_res.pages:
                for block in page.blocks:
                    for line in block.lines:
                        text += " ".join([word.value for word in line.words]) + "\n"
            save_text_to_file(file_name, "DocTR", text)
        except Exception: text = ""
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        results.append({"File": file_name, "Tool": "DocTR", "Time (s)": round(time.time() - t0, 4), "Memory (MB)": round(peak / 10**6, 2), "Chars": len(text.strip())})

    # Surya OCR
    if models_ready.get('SuryaOCR'):
        tracemalloc.start()
        t0 = time.time()
        try:
            text = ""
            # Surya takes PIL images directly
            predictions = surya_rec_predictor(pil_images, det_predictor=surya_det_predictor)
            for page_pred in predictions:
                text += "\n".join([line.text for line in page_pred.text_lines]) + "\n"
            save_text_to_file(file_name, "SuryaOCR", text)
        except Exception as e:
            text = ""
        current, peak = tracemalloc.get_traced_memory()
        tracemalloc.stop()
        results.append({
            "File": file_name, 
            "Tool": "SuryaOCR", 
            "Time (s)": round(time.time() - t0, 4), 
            "Memory (MB)": round(peak / 10**6, 2), 
            "Chars": len(text.strip())
        })
        
    gc.collect()

🚀 Starting Benchmark on target files...

Analyzing: image_based_1.pdf...
Analyzing: image_based_2.pdf...
Analyzing: image_based_3.pdf...
Analyzing: image_based_4.pdf...
Analyzing: image_based_5.pdf...
Analyzing: image_based_6.pdf...
Analyzing: image_based_7.pdf...
Analyzing: image_based_8.pdf...
Analyzing: image_based_9.pdf...
Analyzing: image_based_10.pdf...

In [21]:
# --- 4. Final Output ---
df_resources = pd.DataFrame(results)
print("\n OCR BENCHMARK COMPLETE!")
try:
    from IPython.display import display
    display(df_resources)
except ImportError:
    print(df_resources.to_string())

 OCR BENCHMARK COMPLETE!

                  File       Tool  Time (s)  Memory (MB)  Chars
0    image_based_1.pdf    EasyOCR  248.8737        91.59   3257
1    image_based_1.pdf   RapidOCR   22.4157       121.23   2882
2    image_based_1.pdf  PaddleOCR   80.3958       225.30     29
3    image_based_1.pdf      DocTR    7.3503         3.12   3270
4    image_based_1.pdf   SuryaOCR    0.0001         0.00      0
5    image_based_2.pdf    EasyOCR   32.0410       117.47   1795
6    image_based_2.pdf   RapidOCR    7.2208       150.92   1635
7    image_based_2.pdf  PaddleOCR   67.0111       183.59     29
8    image_based_2.pdf      DocTR    5.9002         2.18   1829
9    image_based_2.pdf   SuryaOCR    0.0000         0.00      0
10   image_based_3.pdf    EasyOCR   38.6784       188.66   2398
11   image_based_3.pdf   RapidOCR    8.9525       164.63   2089
12   image_based_3.pdf  PaddleOCR  105.3513       295.45     29
13   image_based_3.pdf      DocTR    5.8917         4.98   2418
14   image_based_3.pdf   SuryaOCR    0.0000         0.00      0
15   image_based_4.pdf    EasyOCR   46.8151        41.72   1986
16   image_based_4.pdf   RapidOCR    5.7306        56.10   1864
17   image_based_4.pdf  PaddleOCR   54.4118       207.46     29
18   image_based_4.pdf      DocTR   10.5519         2.19   2033
19   image_based_4.pdf   SuryaOCR    0.0001         0.00      0
20   image_based_5.pdf    EasyOCR  111.1296        42.42   1990
21   image_based_5.pdf   RapidOCR    4.7606        57.10   1900
22   image_based_5.pdf  PaddleOCR   50.0582       183.87     29
23   image_based_5.pdf      DocTR    5.3724         2.18   2077
24   image_based_5.pdf   SuryaOCR    0.0001         0.00      0
25   image_based_6.pdf    EasyOCR   22.6184        44.32   1866
26   image_based_6.pdf   RapidOCR    4.4090        61.17   1834
27   image_based_6.pdf  PaddleOCR   53.0660       219.11     29
28   image_based_6.pdf      DocTR    5.5541         2.17   2029
29   image_based_6.pdf   SuryaOCR    0.0000         0.00      0
30   image_based_7.pdf    EasyOCR   31.5667        91.57   3257
31   image_based_7.pdf   RapidOCR    8.8108       121.23   2915
32   image_based_7.pdf  PaddleOCR   77.3526       225.19     29
33   image_based_7.pdf      DocTR    7.4673         3.18   3272
34   image_based_7.pdf   SuryaOCR    0.0000         0.00      0
35   image_based_8.pdf    EasyOCR   23.4320       117.47   1733
36   image_based_8.pdf   RapidOCR    9.5884       150.92   1400
37   image_based_8.pdf  PaddleOCR   61.6407       187.39     29
38   image_based_8.pdf      DocTR    5.7369         2.16   1763
39   image_based_8.pdf   SuryaOCR    0.0001         0.00      0
40   image_based_9.pdf    EasyOCR   22.7132       117.47   1761
41   image_based_9.pdf   RapidOCR   10.2387       150.92   1507
42   image_based_9.pdf  PaddleOCR   57.7478       194.68     29
43   image_based_9.pdf      DocTR    4.5348         2.16   1793
44   image_based_9.pdf   SuryaOCR    0.0000         0.00      0
45  image_based_10.pdf    EasyOCR   31.3874       178.53   2267
46  image_based_10.pdf   RapidOCR   10.2804       150.92   1965
47  image_based_10.pdf  PaddleOCR  160.8300       532.11     29
48  image_based_10.pdf      DocTR    6.6436         8.32   2272
49  image_based_10.pdf   SuryaOCR    0.0000         0.00      0

In [28]:
import os
from jiwer import cer, wer

output_dir = "output_ocr_comparison_new"
target_files = [f"image_based_{i}.pdf" for i in range(1, 11)]

baseline_tool = "DocTR"
comparison_tools = ["EasyOCR", "RapidOCR", "PaddleOCR", "SuryaOCR"]

def load_text(filename):
    path = os.path.join(output_dir, filename)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""

print(f" Relative Agreement Score against (Baseline: {baseline_tool})")
print("=" * 60)

for file_name in target_files:
    baseline_text = load_text(f"{file_name}_{baseline_tool}.txt")
    
    if not baseline_text:
        continue
        
    print(f"\n📄 {file_name}:")
    
    for tool in comparison_tools:
        tool_text = load_text(f"{file_name}_{tool}.txt")
        if tool_text:
            if len(tool_text) == 0:
                print(f"    {tool}: FAILED (0 characters)")
                continue
                
            char_error = cer(baseline_text, tool_text)
            word_error = wer(baseline_text, tool_text)
            
            char_accuracy = max(0, (1 - char_error) * 100)
            word_accuracy = max(0, (1 - word_error) * 100)
            
            print(f"   {tool}: Char Acc: {char_accuracy:.1f}% | Word Acc: {word_accuracy:.1f}%")

 Relative Agreement Score against (Baseline: DocTR)
============================================================

📄 image_based_1.pdf:
   EasyOCR: Char Acc: 95.3% | Word Acc: 61.8%
   RapidOCR: Char Acc: 87.3% | Word Acc: 9.4%
   PaddleOCR: Char Acc: 0.9% | Word Acc: 0.0%

📄 image_based_2.pdf:
   EasyOCR: Char Acc: 90.8% | Word Acc: 43.7%
   RapidOCR: Char Acc: 85.0% | Word Acc: 1.0%
   PaddleOCR: Char Acc: 1.6% | Word Acc: 0.0%

📄 image_based_3.pdf:
   EasyOCR: Char Acc: 94.1% | Word Acc: 52.8%
   RapidOCR: Char Acc: 82.1% | Word Acc: 1.1%
   PaddleOCR: Char Acc: 1.2% | Word Acc: 0.0%

📄 image_based_4.pdf:
   EasyOCR: Char Acc: 90.0% | Word Acc: 31.4%
   RapidOCR: Char Acc: 90.0% | Word Acc: 12.4%
   PaddleOCR: Char Acc: 1.4% | Word Acc: 0.0%

📄 image_based_5.pdf:
   EasyOCR: Char Acc: 71.6% | Word Acc: 3.3%
   RapidOCR: Char Acc: 88.9% | Word Acc: 35.8%
   PaddleOCR: Char Acc: 1.4% | Word Acc: 0.0%

📄 image_based_6.pdf:
   EasyOCR: Char Acc: 70.2% | Word Acc: 0.0%
   RapidOCR: Char Acc: 89.2% | Word Acc: 28.4%
   PaddleOCR: Char Acc: 1.4% | Word Acc: 0.0%

📄 image_based_7.pdf:
   EasyOCR: Char Acc: 95.7% | Word Acc: 63.2%
   RapidOCR: Char Acc: 88.5% | Word Acc: 10.7%
   PaddleOCR: Char Acc: 0.9% | Word Acc: 0.0%

📄 image_based_8.pdf:
   EasyOCR: Char Acc: 92.5% | Word Acc: 53.9%
   RapidOCR: Char Acc: 77.9% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.6% | Word Acc: 0.0%

📄 image_based_9.pdf:
   EasyOCR: Char Acc: 94.1% | Word Acc: 54.5%
   RapidOCR: Char Acc: 83.0% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.6% | Word Acc: 0.0%

📄 image_based_10.pdf:
   EasyOCR: Char Acc: 96.1% | Word Acc: 52.4%
   RapidOCR: Char Acc: 85.6% | Word Acc: 6.0%
   PaddleOCR: Char Acc: 1.3% | Word Acc: 0.0%

Rumus tersebut menggunakan Levenshtein Distance (jarak edit minimum) yang dihitung oleh library jiwer. Metrik dasarnya adalah CER (Character Error Rate) dan WER (Word Error Rate).
S (Substitutions): Jumlah karakter atau kata yang salah dibaca oleh engine (contoh: baseline "Python", OCR membaca "Pyth0n" => S=1).
D (Deletions): Jumlah karakter atau kata pada dokumen asli yang terlewat atau gagal diekstrak (contoh: baseline "Machine Learning", OCR membaca "Machine" => D=1).
I (Insertions): Jumlah karakter atau kata artefak/halusinasi yang muncul pada hasil OCR namun tidak ada di referensi (contoh: baseline "Data", OCR membaca "Data ||" => I=2).
N: Total panjang karakter atau kata pada teks acuan (baseline_text).

Analisis Bias pada Penggunaan Baseline 
Penggunaan model (seperti DocTR) sebagai referensi tanpa verifikasi manual manusia menimbulkan keterbatasan:
a) Potensi Bias:Ketika menetapkan engine tertentu sebagai pembanding utama (pseudo-ground truth), pengujian ini secara teknis mengukur Tingkat Keselarasan/Konsistensi Antar-Model (Inter-model Agreement atau Relative Similarity), alih-alih mengukur Ground Truth Accuracy.
b) Layout Misinterpretation: Jika model baseline membaca dokumen berformat dua kolom secara keliru dari atas ke bawah secara vertikal, sementara engine lain membaca secara horizontal sesuai alur normal manusia, engine uji akan mendapatkan penalti skor akurasi yang buruk meskipun susunan pembacaannya sebenarnya lebih akurat.
c) Insertion Penalties: Jika model baseline gagal mendeteksi bagian teks berukuran kecil di area header atau footer dokumen, namun engine uji berhasil menemukannya, teks tambahan tersebut justru dikalkulasikan oleh jiwer sebagai bentuk kesalahan Insertion atau halusinasi, sehingga menjatuhkan skor akurasi model uji.

In [27]:
import os
from jiwer import cer, wer

output_dir = "output_ocr_comparison_new"
target_files = [f"image_based_{i}.pdf" for i in range(1, 11)]

baseline_tool = "EasyOCR"
comparison_tools = ["DocTR", "RapidOCR", "PaddleOCR", "SuryaOCR"]

def load_text(filename):
    path = os.path.join(output_dir, filename)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""

print(f" ACCURACY COMPARISON (Baseline: {baseline_tool})")
print("=" * 60)

for file_name in target_files:
    baseline_text = load_text(f"{file_name}_{baseline_tool}.txt")
    
    if not baseline_text:
        continue
        
    print(f"\n📄 {file_name}:")
    
    for tool in comparison_tools:
        tool_text = load_text(f"{file_name}_{tool}.txt")
        if tool_text:
            if len(tool_text) == 0:
                print(f"    {tool}: FAILED (0 characters)")
                continue
                
            char_error = cer(baseline_text, tool_text)
            word_error = wer(baseline_text, tool_text)
            
            char_accuracy = max(0, (1 - char_error) * 100)
            word_accuracy = max(0, (1 - word_error) * 100)
            
            print(f"   {tool}: Char Acc: {char_accuracy:.1f}% | Word Acc: {word_accuracy:.1f}%")

 ACCURACY COMPARISON (Baseline: EasyOCR)
============================================================

📄 image_based_1.pdf:
   DocTR: Char Acc: 95.3% | Word Acc: 66.9%
   RapidOCR: Char Acc: 83.5% | Word Acc: 7.7%
   PaddleOCR: Char Acc: 0.5% | Word Acc: 0.0%

📄 image_based_2.pdf:
   DocTR: Char Acc: 90.6% | Word Acc: 56.8%
   RapidOCR: Char Acc: 81.4% | Word Acc: 0.8%
   PaddleOCR: Char Acc: 0.8% | Word Acc: 0.0%

📄 image_based_3.pdf:
   DocTR: Char Acc: 94.0% | Word Acc: 61.2%
   RapidOCR: Char Acc: 77.8% | Word Acc: 0.9%
   PaddleOCR: Char Acc: 0.6% | Word Acc: 0.0%

📄 image_based_4.pdf:
   DocTR: Char Acc: 89.8% | Word Acc: 40.7%
   RapidOCR: Char Acc: 83.7% | Word Acc: 7.1%
   PaddleOCR: Char Acc: 0.8% | Word Acc: 0.0%

📄 image_based_5.pdf:
   DocTR: Char Acc: 70.4% | Word Acc: 19.5%
   RapidOCR: Char Acc: 65.1% | Word Acc: 7.9%
   PaddleOCR: Char Acc: 0.8% | Word Acc: 0.0%

📄 image_based_6.pdf:
   DocTR: Char Acc: 67.6% | Word Acc: 11.5%
   RapidOCR: Char Acc: 62.5% | Word Acc: 4.6%
   PaddleOCR: Char Acc: 0.8% | Word Acc: 0.0%

📄 image_based_7.pdf:
   DocTR: Char Acc: 95.7% | Word Acc: 68.2%
   RapidOCR: Char Acc: 85.2% | Word Acc: 8.8%
   PaddleOCR: Char Acc: 0.5% | Word Acc: 0.0%

📄 image_based_8.pdf:
   DocTR: Char Acc: 92.3% | Word Acc: 61.5%
   RapidOCR: Char Acc: 72.8% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 0.9% | Word Acc: 0.0%

📄 image_based_9.pdf:
   DocTR: Char Acc: 94.0% | Word Acc: 62.3%
   RapidOCR: Char Acc: 78.0% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 0.9% | Word Acc: 0.0%

📄 image_based_10.pdf:
   DocTR: Char Acc: 96.1% | Word Acc: 61.5%
   RapidOCR: Char Acc: 82.3% | Word Acc: 4.5%
   PaddleOCR: Char Acc: 0.7% | Word Acc: 0.0%

In [26]:
import os
from jiwer import cer, wer

output_dir = "output_ocr_comparison_new"
target_files = [f"image_based_{i}.pdf" for i in range(1, 11)]

baseline_tool = "RapidOCR"
comparison_tools = ["DocTR", "EasyOCR", "PaddleOCR", "SuryaOCR"]

def load_text(filename):
    path = os.path.join(output_dir, filename)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return f.read().strip()
    return ""

print(f" ACCURACY COMPARISON (Baseline: {baseline_tool})")
print("=" * 60)

for file_name in target_files:
    baseline_text = load_text(f"{file_name}_{baseline_tool}.txt")
    
    if not baseline_text:
        continue
        
    print(f"\n📄 {file_name}:")
    
    for tool in comparison_tools:
        tool_text = load_text(f"{file_name}_{tool}.txt")
        if tool_text:
            if len(tool_text) == 0:
                print(f"    {tool}: FAILED (0 characters)")
                continue
                
            char_error = cer(baseline_text, tool_text)
            word_error = wer(baseline_text, tool_text)
            
            char_accuracy = max(0, (1 - char_error) * 100)
            word_accuracy = max(0, (1 - word_error) * 100)
            
            print(f"   {tool}: Char Acc: {char_accuracy:.1f}% | Word Acc: {word_accuracy:.1f}%")

 ACCURACY COMPARISON (Baseline: RapidOCR)
============================================================

📄 image_based_1.pdf:
   DocTR: Char Acc: 85.6% | Word Acc: 0.0%
   EasyOCR: Char Acc: 81.4% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.0% | Word Acc: 0.0%

📄 image_based_2.pdf:
   DocTR: Char Acc: 83.2% | Word Acc: 0.0%
   EasyOCR: Char Acc: 79.6% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.8% | Word Acc: 0.0%

📄 image_based_3.pdf:
   DocTR: Char Acc: 79.2% | Word Acc: 0.0%
   EasyOCR: Char Acc: 74.5% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.4% | Word Acc: 0.0%

📄 image_based_4.pdf:
   DocTR: Char Acc: 89.1% | Word Acc: 0.0%
   EasyOCR: Char Acc: 82.6% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.6% | Word Acc: 0.0%

📄 image_based_5.pdf:
   DocTR: Char Acc: 87.9% | Word Acc: 0.0%
   EasyOCR: Char Acc: 63.5% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.5% | Word Acc: 0.0%

📄 image_based_6.pdf:
   DocTR: Char Acc: 88.1% | Word Acc: 0.0%
   EasyOCR: Char Acc: 61.9% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.6% | Word Acc: 0.0%

📄 image_based_7.pdf:
   DocTR: Char Acc: 87.1% | Word Acc: 0.0%
   EasyOCR: Char Acc: 83.5% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.0% | Word Acc: 0.0%

📄 image_based_8.pdf:
   DocTR: Char Acc: 72.1% | Word Acc: 0.0%
   EasyOCR: Char Acc: 66.3% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 2.1% | Word Acc: 0.0%

📄 image_based_9.pdf:
   DocTR: Char Acc: 79.8% | Word Acc: 0.0%
   EasyOCR: Char Acc: 74.3% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.9% | Word Acc: 0.0%

📄 image_based_10.pdf:
   DocTR: Char Acc: 83.4% | Word Acc: 0.0%
   EasyOCR: Char Acc: 79.6% | Word Acc: 0.0%
   PaddleOCR: Char Acc: 1.5% | Word Acc: 0.0%